import React from "react";
export const users = [
  {
    id: 1,
    name: "Somsak Pudonkam",
    role: "Project Manager",
    team: "Development",
    avatar: "/1005383.JPG",
    email: "zoey.lang@example.com",
  },
  {
    id: 2,
    name: "Narongrit Somjai",
    role: "TL",
    team: "Development",
    avatar: "/1005929.JPG",
    email: "jane.fisher@example.com",
  },
  {
    id: 3,
    name: "Niwat Kaennakham",
    role: "Senior Officer",
    team: "Marketing",
    avatar: "/1005450.JPG",
    email: "william.howard@example.com",
  },
  {
    id: 4,
    name: "Montree Kullachote",
    role: "Senior Officer",
    team: "Sales",
    avatar: "/1005539.JPG",
    email: "kristen.cooper@example.com",
  },
  {
    id: 5,
    name: "Nisit Yu",
    role: "Manager",
    avatar: "/1005540.JPG",
    email: "brian.kim@example.com",
    status: "Active",
  },
  {
    id: 6,
    name: "Pitak Ch",
    role: "Senior Officer",
    team: "Design",
    avatar: "/1005562.JPG",
    email: "michael.hunt@example.com",
  },
  {
    id: 7,
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    avatar: "/1005583.JPG",
    email: "samantha.brooks@example.com",
  },
  {
    id: 8,
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    avatar: "/1005529.JPG",
    email: "frank.harrison@example.com",
  },
  {
    id: 9,
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    avatar: "/1006124.JPG",
    email: "emma.adams@example.com",
  },
  {
    id: 10,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    avatar: "/1006252.JPG",
    email: "brandon.stevens@example.com",
  },
  {
    id: 11,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    avatar: "/1006530.JPG",
    email: "megan.richards@example.com",
  },
];
