version: "3.8"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    expose:
      - 80
      - 443
    # volumes:
    #   - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    #   - ./nginx/cert/server.crt:/etc/nginx/cert/server.crt
    #   - ./nginx/cert/server.key:/etc/nginx/cert/server.key
    depends_on:
      - baratsuki_fe
      - baratsuki_be
  baratsuki_fe:
    build: ./frontend
    container_name: baratsuki_fe
    ports:
      - "3000:3000"
    # restart: always
    volumes:
      - ./next-app/:/usr/app/
      - dependencies:/usr/app/node_modules
  baratsuki_be:
    build: ./backend
    container_name: baratsuki_be
    ports: 
      - "8000:8888"
    volumes:
      - ./backend/app/:/code/app/
      - ./backend/:/code/
      - ./backend/requirements.txt:/code/requirements.txt
volumes:
  dependencies:
  fastapi_packages: