version: "3.8"
services:
  baratsuki_fe:
    build: ./frontend
    container_name: baratsuki_fe
    ports:
      - "3000:3000"
    # restart: always
    volumes:
      - ./next-app/:/usr/app/
      - dependencies:/usr/app/node_modules
  baratsuki_be:
    build: ./backend
    container_name: baratsuki_be
    ports: 
      - "8000:8000"
    volumes:
      - ./backend/app/:/code/app/
      - ./backend/:/code/
      - ./backend/requirements.txt:/code/requirements.txt
volumes:
  dependencies:
  fastapi_packages: