data = [
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 20246237305,
        "data": {"ct_actual": 0.0, "prod_actual": 0},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202462300,
        "shift": 1,
    },
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 2024624730,
        "data": {"ct_actual": 0.0, "prod_actual": 0},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202462400,
        "shift": 1,
    },
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 2024625730,
        "data": {"ct_actual": 13.6, "prod_actual": 0},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202462500,
        "shift": 1,
    },
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 2024626730,
        "data": {"ct_actual": 13.6, "prod_actual": 0},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202462600,
        "shift": 1,
    },
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 2024627730,
        "data": {"ct_actual": 13.7, "prod_actual": 0},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202462700,
        "shift": 1,
    },
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 2024628730,
        "data": {"ct_actual": 13.7, "prod_actual": 0},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202462800,
        "shift": 1,
    },
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 20246297301,
        "data": {"ct_actual": 13.7, "prod_actual": 1308},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202462900,
        "shift": 1,
    },
    {
        "section_code": 414273,
        "line_id": 25,
        "machine_no": "6TM-0315",
        "date": 20246307301,
        "data": {"ct_actual": 13.7, "prod_actual": 1308},
        "plan_id": 4,
        "period": [
            {
                "period": "07:35 - 08:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "08:30 - 09:20",
                "hour_no": 2,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "09:20 - 09:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "09:30 - 10:30",
                "hour_no": 3,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "10:30 - 11:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "11:30 - 12:30",
                "hour_no": 0,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "12:30 - 13:30",
                "hour_no": 5,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "13:30 - 14:20",
                "hour_no": 6,
                "duration": 3000,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "14:20 - 14:30",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "14:30 - 15:30",
                "hour_no": 7,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "15:30 - 16:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "16:30 - 16:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 1,
                "plan_type": "B",
            },
            {
                "period": "16:50 - 17:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "17:50 - 19:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 1,
                "plan_type": "N",
            },
            {
                "period": "19:35 - 20:30",
                "hour_no": 1,
                "duration": 3300,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "20:30 - 21:30",
                "hour_no": 2,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "21:30 - 21:40",
                "hour_no": 0,
                "duration": 600,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "21:40 - 22:30",
                "hour_no": 3,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "22:30 - 23:30",
                "hour_no": 4,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "23:30 - 00:20",
                "hour_no": 0,
                "duration": 3000,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "00:20 - 01:30",
                "hour_no": 5,
                "duration": 4200,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "01:30 - 02:30",
                "hour_no": 6,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "02:30 - 02:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "02:50 - 03:30",
                "hour_no": 7,
                "duration": 2400,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "03:30 - 04:30",
                "hour_no": 8,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "04:30 - 04:50",
                "hour_no": 0,
                "duration": 1200,
                "shift_no": 2,
                "plan_type": "B",
            },
            {
                "period": "04:50 - 05:50",
                "hour_no": 9,
                "duration": 3600,
                "shift_no": 2,
                "plan_type": "N",
            },
            {
                "period": "05:50 - 07:20",
                "hour_no": 10,
                "duration": 5400,
                "shift_no": 2,
                "plan_type": "N",
            },
        ],
        "working_date": 202463000,
        "shift": 1,
    },
]
